### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by DataBassGit** [daveshap/ACE_Framework#22]
Link the 1 hour long overview on the root Readme.md.

https://www.youtube.com/watch?v=A_BL_pu4Gtk

Destination: https://github.com/daveshap/ACE_Framework/blob/main/README.md

**Comment by monkrus** [comment]
Since embedding videos requires a thumbnail, where would it be stored?

**Comment by daveshap** [comment]
This is all available under resources. Also, please use better issue titles in the future.
