### ISSUE TITLE
Typo in the ACE Paper + Possible Reference Issue

### ISSUE THREAD

**Issue by ScottzCodez** [daveshap/ACE_Framework#36]
provably  should be	probably

This Reference might be wrong for the following text from the Paper.
  "Neural memory architectures provide dynamic episodic state tracking [ 53 ]"
   Here is the reference   [53] An introduction to variational autoencoders. Foundations and Trends® in Machine Learning
   	In that PDF (book), I Didn't find these words, phrases  
    	---  memory (except in references), Neural memory, memory architectures, state tracking, tracking
       	Found book here --> https://zlib-articles.se/book/79113047/78c0f8

**Comment by daveshap** [comment]
Passed it up the chain, thanks
