### ISSUE TITLE
aspirational layer documentation confusion

### ISSUE THREAD

**Issue by draconicfae** [daveshap/ACE_Framework#76]
At the end of the "Layer 1 Aspirational Layer" section of ACE_Framework.md it says "got it, here is an expanded version:" and then proceeds to "Layer 2: Global Strategy Layer".  Is this saying that the Global Strategy Layer is an expanded version of the Aspirational Layer?  Or was there originally another text block after the ':' which was then deleted prior to the original upload?

**Comment by daveshap** [comment]
Fixed
