### ISSUE TITLE
API INTERACTION SCHEMA north vs. south clarification?

### ISSUE THREAD

**Issue by kevon217** [daveshap/ACE_Framework#80]
Not sure if this is a small bug or I failed to grasp a concept, but it seems the initial description under the _## API INTERACTION SCHEMA_ prompt mixes up the North and South bus roles. For example in **layer2.txt**

_# API INTERACTION SCHEMA
The USER will give you logs from the NORTH and SOUTH bus. Information from the SOUTH bus should be treated as lower level telemetry from the rest of the ACE. Information from the NORTH bus should be treated as imperatives, mandates, and judgments from on high. Your output will be two-pronged._ 

My understanding is that the SOUTH bus is coming from on high and the NORTH bus represents lower-level telemetry. Should the above prompt swap NORTH and SOUTH? 

Also, just wanted to say I love the work you all are doing and am very excited to see this framework built out. I'm particularly looking forward to how this will be realized with a UI and management system.

**Comment by daveshap** [comment]
Looks like yeah I got that wrong, thanks. Will correct it... eventually lol
